version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/horixonio/.go-template"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "test-coverage"